---
- hosts: all
  remote_user: root
  gather_facts: no

  vars:
  - username: user1
  - groupname: group1

  tasks:
  - name: create group
    group: name={{ groupname }} state=present
  - name: create user
    user: name={{ username }} state=present
